//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Russell.RADAR.POC.WebApp.OpinionDocuments {
    
    
    public partial class EditDocument {
        
        /// <summary>
        /// linkOutput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton linkOutput;
        
        /// <summary>
        /// ddlOverallRank control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlOverallRank;
        
        /// <summary>
        /// textBoxOverall control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxOverall;
        
        /// <summary>
        /// textBoxDiscussion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxDiscussion;
        
        /// <summary>
        /// SectionInvestementStaff control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionInvestementStaff;
        
        /// <summary>
        /// SectionOrganizationalStability control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionOrganizationalStability;
        
        /// <summary>
        /// SectionAssetAllocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionAssetAllocation;
        
        /// <summary>
        /// SectionResearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionResearch;
        
        /// <summary>
        /// SectionCountrySelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionCountrySelection;
        
        /// <summary>
        /// SectionPortfolioConstruction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionPortfolioConstruction;
        
        /// <summary>
        /// SectionCurrencyManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionCurrencyManagement;
        
        /// <summary>
        /// SectionImplementation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionImplementation;
        
        /// <summary>
        /// SectionSecuritySelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionSecuritySelection;
        
        /// <summary>
        /// SectionSellDiscipline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Russell.RADAR.POC.WebApp.OpinionDocuments.Components.SectionEditor SectionSellDiscipline;
        
        /// <summary>
        /// buttonOk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonOk;
        
        /// <summary>
        /// buttonCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonCancel;
    }
}
