using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3603
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Russell")]
[assembly: AssemblyProductAttribute("Russell.RADAR.POC")]
[assembly: AssemblyCopyrightAttribute("Copyright Russell 2010")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("10.1.14.3467")]
[assembly: AssemblyFileVersionAttribute("10.1.14.3467")]

